# Day2

## 1.제어문(프로그램의 구조를 쌓는다)
1. if
- 조건식 결과에 따라서 서로 다른 코드를 실행 
    - True인 경우 if 구역 실행
    - False인 경우 else 구역 실행
- if : 조건식의 결과가 참이면 본인의 구역을 실행
- elif (else + if) : 앞선 조건식의 결과가 거짓이면서 본인 조건식의 결과가 참이면 본인의 구역을 실행
- else : 앞선 조건식의 결과가 거짓이면 본인의 구역 실행
- 구역은 들여쓰기를 이용해서 지정
2. while
  - 특정조건을 만족하는 동안 실행하는 반복문
3. for
  - 특정 코드를 여러번 실행시키고 싶을때 사용한다.
  - range을 이용한 for 문은 데이터를 만들수 있다.
  

  - <기본 형태>
  - for 변수 in 리스트(또는 튜플, 문자열):
    수행할 문장1
    수행할 문장2
    ...
    
  - 리스트의 요소를 변수의 순서대로 대입하면서 실행한다.

## 2.함수
- 위치인수, 위치를 기반으로 값을 전환한다.
- 기본인수 
- 키워드인수, 이름을 기준으로 값을 전달한다. 순서상관없음
- 가변 매개변수 (*는 튜플로 저장, ** 딕셔너리 형태로 저장)

## 3.모듈

- 모듈은 확장자를 뺸 나머지 이름이다.
- import __a___ as ____(별칭)= 
- from __a___ import _____ = 
- from ___a___ import * = a모듈내에 전체 모듈 다 가져온다.

-------------------여기까지가 퀴즈시험범위이고 6문제가 나온다-----------

### 3-1 numpy
1. reshape: 형태를 자유자제로 변경한다. 단 부피가 같아야 한다. -1은 알아서 계산해 준다.
 - np.reshape = array를 지정해 줘야한다.
 - array.reshape = 그냥 사용가능하다.
 
2. indexing
 - 대괄호를 한번만 사용한다 [1,0]
 - 조건 인덱싱 =필터 
 - 팬시인덱싱 = 포인트로 지정한다. (판다스는 선형형태이다)

3. where : 특정조건을 만족하는 위치 반환
 - np.where ~~

4. 랜덤으로 만드는 방법
 - np.rando.seed(숫자)
   draws = np.random.randint(a,b,c) a=시작, b=끝(생략),c= 개수
   
5. 변수를 저장하는 방법
 - 이름 = 함수
   이름(실행) -> 어떤 함수에 대한 값을 출력하기 위해서는 필수이다.
   
6. 기타
 - steps.cumsum() : steps 배열에 누적합
 - np.min(데이터) : 데이터의 최소값
 - np.max(데이터) : 데이터의 최대값
 - np.abs(데이터) : 음수를 양수로 변경
 - 데이터 = 데이터 >= 숫자 : 숫자이상인 경우 참,거짓으로 반환
 - 데이터.argmax() : 최대값을 조회
-------------------인증시험에서는 2문제 나온다. ----------------

In [2]:
test_score = [1,2,3,4,5,6]

for i in test_score:
    print(i)

1
2
3
4
5
6


In [4]:
test_score = [1,2,3,4,5,6]

for n in test_score: #알파벳은 아무거나 넣어도 무관하다.
    print(n) 

1
2
3
4
5
6


In [6]:
for n in "hello":
    print(n)

h
e
l
l
o


In [7]:
시험결과 = [11,45,23,12,67,89]

for score in 시험결과:
    if score >= 60:
        print("합격")
    else:
        print("불합격")

불합격
불합격
불합격
불합격
합격
합격


In [10]:
용소율몸무게 = [5,7,9,11,15]

for 몸무게 in 용소율몸무게:
    if 몸무게 >= 10:
        print("과체중")
    else:
        print("정상체중")

정상체중
정상체중
정상체중
과체중
과체중


## range 를 이용한 for문
- 사용방법: range (start,stop, step)
- range (x) (start =0,stop=x, step=1)
- range (x,y) (start =x,stop=y, step=1) 


In [11]:
range(1,101) # 컴퓨터는 아래와 같이 인식 한다. 마지막숫자는 빠진다 즉 100으로 끝

range(1, 101)

In [12]:
list(range(1,101)) #리스트 타입으로 변환해서 확인

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [14]:
total = 0 #num 변수를 값을 더해서 저장할 공간
for num in range(1,101):
    total = total + num
total

5050

In [15]:
sum(range(1,101))

5050

In [24]:
gugu = 2

for n in range(1,10):
    print(gugu * n)

2
4
6
8
10
12
14
16
18


In [26]:
for n in range(1,10):
    print(2,"x",n,"=",2*n)

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18


In [28]:
gugu = 3

for n in range(1,10):
    print(gugu,"x",n,"=",gugu * n)

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27


In [29]:
#중첩 반복문으로 위에를 정리할수 있다.
for gugu in range(2,10):
    for n in range(1,10):
        print(gugu,"x",n,"=",gugu * n)
        
#이렇게 이중으로 반복이 가능하다.

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [30]:
for i in ['a','b']:
    for j in [1,2,3]:
        print(i,j)

a 1
a 2
a 3
b 1
b 2
b 3


In [45]:
room = [[101,102],[201,202],[301,302]] #이중리스트

for i in room:
    for r in i:
        print(r, end=" ")
    print() #프린트를 앞으로 한칸 밀어줘야 한다.

101 102 
201 202 
301 302 


In [47]:
for d1,d2 in room:
    print(d1,d2)

101 102
201 202
301 302


In [49]:
data = ['a',10],['b',20],['c',30]
for a,n in data:
    print(a,n)

a 10
b 20
c 30


In [53]:
for n in range(1,11):
    
    if n%2 ==0: #짝수
        continue #계속 진행된다
    if n ==5:
        break #진행을 끝낸다.
    print(n)

1
3


In [55]:
for i in range(1,101):
    pass # 계념만 잡아놨을때 오류를 방지하는 방법
    

In [56]:
marks = [90, 25, 67, 45, 80]

number = 0 
for mark in marks: 
    number = number +1 
    if mark >= 60: 
        print("%d번 학생은 합격입니다." % number)
    else: 
        print("%d번 학생은 불합격입니다." % number)

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 합격입니다.
4번 학생은 불합격입니다.
5번 학생은 합격입니다.


In [61]:
tests = [90,88,77,92,83]

num = 0
for test in tests:
    num = num +1
    if test >=90:
        print("%d번 학생은 합격입니다." %num)
    else:
        print("%d번 학생은 불합격입니다." %num)

1번 학생은 합격입니다.
2번 학생은 불합격입니다.
3번 학생은 불합격입니다.
4번 학생은 합격입니다.
5번 학생은 불합격입니다.


## 2.함수
- 함수의 정의 : 생성
- 함수의 호출 : 실행
 - return : 1. 함수를 종료한다.(함수를 호출한 곳으로 돌아간다)
 - 만약 return이 없으면 none 으로 리턴 한다.

In [1]:
def add(a,b):
    return a + b

In [3]:
res = add(10,20) #함수는 한번 만들면 계속 실행 할수 있는 툴이다.
print(res)

30


In [5]:
def add(a,b):
    print(a+b)
res = add(10,20) 
print(res)

30
None


In [8]:
def func(a,b):
    res = a+b
    return res #리턴에 값이 있으면 값이 함수를 부른곳으로 이동
print(func(10,20))

30


In [9]:
def func(a,b):
    res = a+b #리턴이 없거나 값이 없으면 none으로 끝난다.
   
print(func(10,20))

None


# 2-1.함수호출(값전달)
- 위치인수 (개수가 일치해야한다!)
- 기본인수 
- ***키워드 매개변수 (순서에 상관없이 이름을 통해 명시 전달)

In [2]:
#위치인수
def ilgu(a,b):
    return(a+b)
def ilgu2(a,b):
    return(a*b)
print(ilgu(3,4)) #각각 출력하려면 프린트 해야한다.
print(ilgu2(3,4))

7
12


In [ ]:
#기본인수 (default)

In [23]:
def add(a,b):
    result = a+b
    print(f'a:{a},b:{b}')
    return result

add(1,2)

#각각 돌려준다.즉 리턴은 값을 돌려주는 매개이다.


a:1,b:2


3

In [3]:
#가변매개 변수 
#= *args (별표가 붙어있으면 가변 -> tuple로 데이터가 들어온다.)

In [10]:
def add(*args): #* 넣으면 튜블을 모두 연산 가능하다.
    sum = 0
    for i in args:
        sum +=i
    return sum

print(add(1,2,3))
v=[1,2,3]
print(add(*v))

6
6


In [23]:
def func(a,b=0):
    print(f'a:{a} b:{b}')

In [30]:
func(10)
func(a=19) # 변수가 있는 b는 없어도 가능. 그러나 a는 있어야 한다.

#중요!!  a와 같이 아무런 변수가 없으면 값을 꼭 넣어줘야 한다.

a:10 b:0 c:()
a:19 b:0 c:()


In [ ]:
def func(a, b=0):
    print(f'a : {a} b: {b}')
func(10) # 위치
func(a=2) # 키워드
func(10, 20)
func(a=2, b=3)
func(10, b=2) # 순서는 위치부터 사용 키워드


In [ ]:
def func2(a, b=0, *c): # c : 가변매개변수 (생략가능)
    print(f'a : {a} b : {b} c : {c}')
func2(10)
func2(10, 20)
func2(10, 20, 30)
func2(10, 20, 30, 40)
func2(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
#func2(10, b=20, 20, 30, 40) # 오류 (키워드는 위치 뒤에 와야함)

In [ ]:
def func3(a, b=0, *c, **d):
        print(f'a : {a} b : {b} c : {c} d : {d}')
func3(1, 2, 3, 4, 5, 6, a1=10, a2=20, a3=30)


In [42]:
def calc_many(choice, *args):
    print(f'choice:{choice} args:{args}')
    if choice == 'sum':
        total = 0
        for data in args:
            total = total +data
        return total
    elif choice =='mul':
        total = 1
        for data in args:
            total = total +data
        return total
    else:
        print("알수없음")

print(calc_many('sum',1,2,3,4,5,))
print(calc_many('mul',1,2,3,4,5,))

choice:sum args:(1, 2, 3, 4, 5)
15
choice:mul args:(1, 2, 3, 4, 5)
16


In [41]:
# def calc_many(choice, *args) 함수에서 choice 가 sum 이면 합을 구해서 리턴하고
# choice 가 mul 이면 곱한 결과를 리턴하는 함수를 구현하세요
def calc_many(choice, *args):
    # choice 가 sum 이면 합을 구해서 리턴
    if choice == 'sum':
        total = 0 
        for data in args:
            total = total + data
        return total
    # choice 가 mul 이면 곱한 결과를 리턴
    elif choice == 'mul':
        total = 1 
        for data in args:
            total = total * data
        return total
    else:
        print('알 수 없는 명령어')
print(calc_many('sum', 1,2,3,4,5)) # 15
print(calc_many('mul', 1,2,3,4,5)) # 120

15
120


In [44]:
# def calc_many(choice, *args) 함수에서 choice 가 sum 이면 합을 구해서 리턴하고
# choice 가 mul 이면 곱한 결과를 리턴하는 함수를 구현하세요
def calc_many(choice, *args):
    print(f'choice{choice} args{args}')
    
    if choice == 'sum':
        base = 0
        for data in args:
            base = base + data
        return base
    elif choice =='mul':
        base = 1
        for data in args:
            base = base + data
        return base
    else:
        print("값이 잘못됨")
print(calc_many('sum', 1,2,3,4,5,))

choicesum args(1, 2, 3, 4, 5)
15


In [64]:
# def calc_many(choice, *args) 함수에서 choice 가 sum 이면 합을 구해서 리턴하고
# choice 가 mul 이면 곱한 결과를 리턴하는 함수를 구현하세요

#자 하나하나 해보자

def clc_many(choice, *args):
    if choice == 'sum':
        total = 0
        for data in args:
            total = total +data
        return total
    
    elif choice == 'mul':
        total = 0
        for data in args:
            total = total +data
        return total
    
    else:
        print("?")
        
print(clc_many('sum', 1,2,3,4,5))
print(clc_many('mul', 1,2,3,4,5))
print(clc_many('1', 1,2,3,4,5))
print(clc_many('mul', 1,2,3,4,5))

#none 은 왜 생기는 거지?? 분명 리턴을 다 채웠는데?
     

15
15
?
None
15


모듈 사용하기

파일명이 mysuni.py 이면 모듈명은 mysuni 임
이미 파이선3이세 300개가 넘는 모듈이 있다.
pip install 모듈명 (다운로드 가능)

# ****모듈 로딩하는 방법


1. 전체를 가져오는 것 
 - import 모듈명
  import numpy as np
  np.array
2. 일부 가져오는 것 
 - from 모듈명 import 함수 (as 약칭 가능)
 - 모듈 > 함수 (모듈.함수 로 명령해서 특정 함수를 쓴다)
 from numpy import array
 
3. *는 전체를 불러오는 것이다.


내일 퀴즈는 
for 반복문 , 함수, 모듈

인증시험은 변수, 모듈까지 6문제 나올거임

In [66]:
!pip install numpy

In [67]:
#numpy 가져오기 (넘파이는 비정형 데이터를 지원한다.)

import numpy as np


In [70]:
#1차원 배열
array = np.array([1,2,3,4,5])
array, type(array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [80]:
#2차원 배열
array = np.array([[1,2,3],[2,3,4],[3,5,8]])
array

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 8]])

numpy 에서 중요한 것이 3가지인데 (넘파이는 비정형 데이터를 지원한다.)
1. shape
2. indexing 
 - 팬시 -> 목록
 - 
3. slicing



In [81]:
array

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 8]])

In [82]:
array.reshape(9,)

array([1, 2, 3, 2, 3, 4, 3, 5, 8])

In [83]:
array.reshape(1,3,3) #개수,행,열

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 5, 8]]])

In [84]:
array.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [5],
        [8]]])

In [87]:
array = np.arange(32)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [92]:
arr.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [93]:
array = np.arange(9).reshape(3,3)
array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 조건인덱싱

- [1,2,3] -> (int array)
- [1.0,2.0,3.0] -> (float array)
- [1시,2시,3시] -> (object array)
- True, False 값을 가지는  (boolean array) 마스킹이랑 비슷함 형태가 같아야함

In [97]:
array %2

bidx = array %2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [98]:
array[bidx]

array([0, 2, 4, 6, 8])

In [100]:
array[array >5]

array([6, 7, 8])

numpy = 포인트 좌표로 추출
pandas = 선형 좌표로 추출

In [101]:
np.random.seed(0)
arr = np.random.randn(10)
arr

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [102]:
#음수값의 위치 파악 

np.where(arr<0)

(array([5, 7, 8]),)

In [ ]:
#조건에 따라변경

np.where(arr < 0, 0, arr) # 음수인 경우 0으로 아닌 경우 원래 값 사용

#결측치 제거가 가능한 방법!`!!! 드디어 찾아냄

In [103]:
!pip install mysuni

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 5.4 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 KB 745.4 kB/s eta 0:00:001m896.3 kB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.8/292.8 KB 2.6 MB/s eta 0:00:00 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 4.8 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 6.1 MB/s eta 0:00:00m eta 0:00:010:00:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 898.1/898.1 KB 4.1 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.3/59.3 KB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 3.2 MB/s eta 0:00:00 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 KB 3.7

In [104]:
from mySUNI import cds
cds.list_workshop()

워크샵
0        mySUNI-WorkShop-00-Python
1      mySUNI-WorkShop-01-StepWalk
2        mySUNI-WorkShop-02-Pandas
3   mySUNI-WorkShop-03-타이타닉 생존자 분석
4   mySUNI-WorkShop-04-타이타닉 생존자 예측
5  mySUNi-WorkShop-05-데이터 전처리 및 분석
6  mySUNI-WorkShop-06-웨이퍼 불량 유형 분류
7    mySUNI-WorkShop-07-따릉이 대여량 예측
8        mySUNI-WorkShop-08-집 값 예측
9       mySUNI-WorkShop-09-머신러닝 연습

In [105]:
cds.download_workshop('mySUNI-WorkShop-01-StepWalk', local=True)


워크샵: ['mySUNI-WorkShop-01-StepWalk-실습.ipynb']
파일 정보

저장 위치:	 workshop/mySUNI-WorkShop-01-StepWalk/mySUNI-WorkShop-01-StepWalk-실습.ipynb



In [106]:
cds.download_workshop('mySUNI-WorkShop-01-StepWalk', sol=True,local=True)

워크샵: ['mySUNI-WorkShop-01-StepWalk-해설.ipynb']
파일 정보

저장 위치:	 workshop/mySUNI-WorkShop-01-StepWalk/mySUNI-WorkShop-01-StepWalk-해설.ipynb



In [ ]:
(a)


In [1]:
def func(a,b):
    res = a+b
    return res

print(func(10,20))

30
