In [1]:
from IPython.core.display import display, HTML
# 노트북 컨테이너 크기 조절
display(HTML("<style>#notebook-container {width: 90% !important; }</style>"))
# 마크다운 폰트
display(HTML("<style>.rendered_html{font-family: 'D2Coding'; font-size: 16pt; line-height: 140%;}</style>"))
# DataFrame 테이블 폰트
display(HTML("<style>.rendered_html table{font-family: 'D2Coding'; font-size: 16pt; line-height: 140%;}</style>"))
# 출력창 폰트
display(HTML("<style>pre{font-family: 'D2Coding', font-size: 16pt;}.rendered_html>ul>li{margin: 10px}</style>"))
display(HTML("<style>div.output_area>pre, div.output_subarea>pre{font-size: 16pt !important; line-height: 140%;}</style>"))
# 코드셀 폰트
display(HTML("<style> .CodeMirror pre {font-family: 'D2Coding'; font-size: 18pt !important; line-height: 140%;}</style>"))

# for 반복문
- iterable 요소를 하나씩 변수에 대입하면서 for 구역의 코드를 실행
    - iterable 요소의 개수 == 반복 횟수

```python
for 변수 in iterable:
    반복할 코드
    반복할 코드
```

In [2]:
for n in [1, 2, 3, 4, 5]:
    print(n)

1
2
3
4
5


In [3]:
for d in "Hello":
    print(d)

H
e
l
l
o


In [4]:
result = [90, 35, 68, 44, 81] # 5명의 점수
for score in result:
    if score >= 60:
        print("합격")
    else:
        print("불합격")

합격
불합격
합격
불합격
합격


In [6]:
# range() 함수를 이용하여 1 부터 100 까지의 합을 출력하세요
range(1, 101) # range type으로 만들어짐
list(range(1, 101)) # list type으로 변경 (확인 용도)

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [7]:
total = 0 # num 변수의 값을 더해서 저장할 공간
for num in range(1, 101):
    total = total + num
total

5050

In [11]:
print(2, "X", 1, "=", 2*1)
print(2, "X", 2, "=", 2*2)
print(2, "X", 3, "=", 2*3)
print(2, "X", 4, "=", 2*4)
print(2, "X", 5, "=", 2*5)
print(2, "X", 6, "=", 2*6)
print(2, "X", 7, "=", 2*7)
print(2, "X", 8, "=", 2*8)
print(2, "X", 9, "=", 2*9)

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


In [12]:
for n in range(1, 10):
    print(2, "X", n, "=", 2*n)

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


In [13]:
# 중첩반복문 (이중반복문)
for dan in range(2, 10):
    for n in range(1, 10):
        print(dan, "X", n, "=", dan*n)

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81


In [14]:
room = [[101, 102], [201, 202], [301, 302]] # 이중리스트
for row in room:
    for r in row:
        print(r)

101
102
201
202
301
302


In [16]:
room = [[101, 102], [201, 202], [301, 302]] # 이중리스트
for row in room:
    for r in row:
        print(r, end=" ")
    print()

101 102 
201 202 
301 302 


In [18]:
for d1, d2 in room:
    print(d1, d2)

101 102
201 202
301 302


In [19]:
n1, n2, n3 = [1, 2, 3]
print(n1, n2, n3)

1 2 3


In [21]:
data = [['A', 10], ['B', 20], ['C', 30]]
for a, n in data:
    print(a, n)

A 10
B 20
C 30


In [27]:
for n in range(1, 11):
    if n % 2 == 0: # 짝수
        continue # 반복문 구역에서만 사용 가능 (다음 단계로 건너뜀)
    if n == 5:
        break # 반복문 구역에서만 사용 가능 (본인이 속한 반복문을 종료)
    print(n)

1
3


In [32]:
data = ['1', '2', '3', '4', '5']
answer = []
for d in data:
    answer.append(int(d))
answer

[1, 2, 3, 4, 5]

In [35]:
data = ['1', '2', '3', '4', '5']
answer = [int(d) for d in data]
answer

[1, 2, 3, 4, 5]

# 함수

In [37]:
# 두개의 변수를 입력받아 + 결과를 반환
def add(a, b):
    return a + b

In [38]:
res = add(10, 20)
print(res)

30


In [39]:
res = add('a', 'b')
print(res)

ab


In [40]:
def add(a, b):
    print(a + b)
res = add(10, 20)
print(res)

30
None


In [43]:
def func(a, b):
    res = a + b
    return res
print(func(10, 20))

30


In [45]:
# 함수 정의(생성)
def add(a, b):
    print(f'a : {a} b: {b}')
    return a + b

In [48]:
# 위치매개변수
res = add(10, 20) # 순서대로 값이 대입 (개수 일치)
print(res)

a : 10 b: 20
30


In [51]:
# 키워드매개변수
res = add(b=10, a=20) # 이름대로 값이 대입 (개수 일치, 이름 일치)
print(res)

a : 20 b: 10
30


In [53]:
def add(a, b=0): # b 변수는 기본값 설정 (생략가능)
    print(f'a : {a} b: {b}')
    return a + b
add(a=20), add(10)

a : 20 b: 0
a : 10 b: 0


(20, 10)

In [55]:
def func(a, b=0):
    print(f'a : {a} b: {b}')
func(10) # 위치
func(a=2) # 키워드
func(10, 20)
func(a=2, b=3)
func(10, b=2) # 순서는 위치부터 사용 키워드

In [65]:
def func2(a, b=0, *c): # c : 가변매개변수 (생략가능)
    print(f'a : {a} b : {b} c : {c}')
func2(10)
func2(10, 20)
func2(10, 20, 30)
func2(10, 20, 30, 40)
func2(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)
#func2(10, b=20, 20, 30, 40) # 오류 (키워드는 위치 뒤에 와야함)

a : 10 b : 0 c : ()
a : 10 b : 20 c : ()
a : 10 b : 20 c : (30,)
a : 10 b : 20 c : (30, 40)
a : 10 b : 20 c : (30, 40, 50, 60, 70, 80, 90, 100)


In [66]:
def func3(a, b=0, *c, **d):
        print(f'a : {a} b : {b} c : {c} d : {d}')
func3(1, 2, 3, 4, 5, 6, a1=10, a2=20, a3=30)

a : 1 b : 2 c : (3, 4, 5, 6) d : {'a1': 10, 'a2': 20, 'a3': 30}


In [70]:
# def calc_many(choice, *args) 함수에서 choice 가 sum 이면 합을 구해서 리턴하고
# choice 가 mul 이면 곱한 결과를 리턴하는 함수를 구현하세요
def calc_many(choice, *args):
    # choice 가 sum 이면 합을 구해서 리턴
    if choice == 'sum':
        total = 0 
        for data in args:
            total = total + data
        return total
    # choice 가 mul 이면 곱한 결과를 리턴
    elif choice == 'mul':
        total = 1 
        for data in args:
            total = total * data
        return total
    else:
        print('알 수 없는 명령어')
print(calc_many('sum', 1,2,3,4,5)) # 15
print(calc_many('mul', 1,2,3,4,5)) # 120

15
120


# numpy

In [76]:
# numpy 모듈 설치
!pip install numpy

You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.


In [77]:
# numpy 모듈을 불러오기
import numpy as np

In [80]:
# 1차원 배열 생성
array = np.array([1, 2, 3, 4, 5])
array, type(array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [81]:
# 2차원 배열 생성
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
# array의 속성 조회
array.ndim # 차원수

2

In [84]:
# shape : 배열의 형태 
array.shape

(3, 3)

In [85]:
# size : 데이터 개수
array.size

9

In [86]:
# dtype : 데이터 유형(타입)
array.dtype

dtype('int64')

In [87]:
# T : 행 <-> 열
array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [88]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
array.reshape(9,) # (9, ) 형태로 변환

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
array.reshape(1, 3, 3) # (1, 3, 3) 형태로 변환

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [91]:
arr = np.arange(32) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [97]:
arr.reshape(4, 8) # 4행 8열
arr.reshape(8, 4) # 8행 4열
arr.reshape(-1, 4) # -1행 4열 > -1 : 1번만 사용 (자동 계산, 32 / 4 = 8) 
arr.reshape(16, -1) # 16행 ?열 > 2열

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [101]:
array % 2 # 배열의 요소를 2로 나머지 연산
bidx = array % 2 == 0 # 배열의 요소가 0과 같으면 True 아니면 False
bidx

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [102]:
array[bidx] # array에서 짝수만 선택

array([2, 4, 6, 8])

In [103]:
array[array % 2 == 0]

array[array >= 5]

array([2, 4, 6, 8])

In [110]:
np.random.seed(0)
arr = np.random.randn(10)
arr

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [112]:
# 음수값의 위치 파악
np.where(arr < 0)

# 조건에 따라서 값 변경
np.where(arr < 0, 0, arr) # 음수인 경우 0으로 아닌 경우 원래 값 사용

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799,
       0.        , 0.95008842, 0.        , 0.        , 0.4105985 ])

In [113]:
!pip install mySUNI

You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.


In [114]:
from mySUNI import cds
cds.list_workshop() # 워크샵 목록 조회

워크샵
0        mySUNI-WorkShop-00-Python
1      mySUNI-WorkShop-01-StepWalk
2        mySUNI-WorkShop-02-Pandas
3   mySUNI-WorkShop-03-타이타닉 생존자 분석
4   mySUNI-WorkShop-04-타이타닉 생존자 예측
5  mySUNi-WorkShop-05-데이터 전처리 및 분석
6  mySUNI-WorkShop-06-웨이퍼 불량 유형 분류
7    mySUNI-WorkShop-07-따릉이 대여량 예측
8        mySUNI-WorkShop-08-집 값 예측
9       mySUNI-WorkShop-09-머신러닝 연습

In [115]:
cds.download_workshop('mySUNI-WorkShop-01-StepWalk') # 워크샵 다운로드 (엘리스 환경 O)
#cds.download_workshop('mySUNI-WorkShop-01-StepWalk', local=True) # 워크샵 다운로드 (엘리스 환경 X)

워크샵: ['mySUNI-WorkShop-01-StepWalk-실습.ipynb']
파일 정보

저장 위치:	 /mnt/elice/workshop/mySUNI-WorkShop-01-StepWalk/mySUNI-WorkShop-01-StepWalk-실습.ipynb



In [116]:
cds.download_workshop('mySUNI-WorkShop-01-StepWalk', sol=True) # 해설 파일 다운로드

워크샵: ['mySUNI-WorkShop-01-StepWalk-해설.ipynb']
파일 정보

저장 위치:	 /mnt/elice/workshop/mySUNI-WorkShop-01-StepWalk/mySUNI-WorkShop-01-StepWalk-해설.ipynb

